language: java
jdk: oraclejdk8
sudo: false

script:
  - ./mvnw verify -Dspring.profiles.active=travis -Dspring.output.ansi.enabled=always

services:
  - docker

cache:
  directories:
    - .autoconf
    - $HOME/.m2

env:
  global:
    - GOOGLE_APPLICATION_CREDENTIALS=~/gcloud-service-key.json

before_deploy:
  - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD

deploy:
  - provider: script
    script: chmod +x ./deploy.sh &&  ./deploy.sh
    skip_cleanup: true
    on:
      branch: master